spring:
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    username: admin
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:DB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect